service: twit

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: eu-west-2


functions:
  reply:
    handler: handler.reply

plugins:
  - serverless-python-requirements

custom:
  requirements:
    - -r requirements.txt